"""bikes and bike images

Revision ID: e4b8680e9072
Revises: 2a5a6ae0dfae
Create Date: 2026-08-14 00:25:50.164942

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e4b8680e9072'
down_revision: Union[str, Sequence[str], None] = '2a5a6ae0dfae'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('bikes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('owner_id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=140), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('make', sa.String(length=60), nullable=False),
    sa.Column('model', sa.String(length=60), nullable=False),
    sa.Column('year', sa.Integer(), nullable=False),
    sa.Column('category', sa.String(length=20), nullable=False),
    sa.Column('engine_cc', sa.Integer(), nullable=True),
    sa.Column('mileage', sa.Integer(), nullable=True),
    sa.Column('transmission', sa.String(length=20), nullable=True),
    sa.Column('price_per_day', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('security_deposit', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('city', sa.String(length=80), nullable=False),
    sa.Column('state', sa.String(length=40), nullable=False),
    sa.Column('address', sa.String(length=255), nullable=True),
    sa.Column('latitude', sa.Float(), nullable=True),
    sa.Column('longitude', sa.Float(), nullable=True),
    sa.Column('status', sa.String(length=12), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['owner_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('bikes', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_bikes_category'), ['category'], unique=False)
        batch_op.create_index(batch_op.f('ix_bikes_city'), ['city'], unique=False)
        batch_op.create_index(batch_op.f('ix_bikes_owner_id'), ['owner_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_bikes_status'), ['status'], unique=False)

    op.create_table('bike_images',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('bike_id', sa.Integer(), nullable=False),
    sa.Column('path', sa.String(length=512), nullable=False),
    sa.Column('is_primary', sa.Boolean(), nullable=False),
    sa.Column('sort_order', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['bike_id'], ['bikes.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('bike_images', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_bike_images_bike_id'), ['bike_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('bike_images', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_bike_images_bike_id'))

    op.drop_table('bike_images')
    with op.batch_alter_table('bikes', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_bikes_status'))
        batch_op.drop_index(batch_op.f('ix_bikes_owner_id'))
        batch_op.drop_index(batch_op.f('ix_bikes_city'))
        batch_op.drop_index(batch_op.f('ix_bikes_category'))

    op.drop_table('bikes')
    # ### end Alembic commands ###
